fn main() {
    // A basic error-type
    let mut x: String!Int = .ok(4)

    // Setting to `.err()` indicates an error
    x = .err("Something bad happened!")

    // Setting to `.ok()` indicates a successful value
    x = .ok(113)
    debug::assert(x.ok == 113)

    // catch returns the lhs if it's not .err, or else returns the rhs
    let y: String!Int = .err("Computer exploded")
    debug::assert(y catch 45 == 45)
}